### ISSUE TITLE
Would you consider adding a license?

### ISSUE THREAD

**Issue by onyx-and-iris** [dgparker/lilproxy#1]
Hi, great package! 

Would you be willing to add a license file?

https://choosealicense.com/no-permission/

Thanks.

**Comment by dgparker** [comment]
Hello thanks for the kind words. I can add a license for this. Out of curiousity - What/Where are you planning to leverage this?

**Comment by onyx-and-iris** [comment]
Great news. Quake3 Engine games tie the rcon port to the public port of the server. I can use your proxy to separate the two, I'd likely modify it a little to accept only quake3 rcon/query packets.

**Comment by dgparker** [comment]
license added

**Comment by onyx-and-iris** [comment]
Thanks!
